### ISSUE TITLE
Add ability to load multiple rasters onto the map

### ISSUE THREAD

**Issue by 2320sharon** [Doodleverse/seg2map#4]
Users are going to want to load a merged_multispectural tif for each year they download imagery for. `leafmap`'s default method to load rasters onto the map `load_raster` takes about 15 seconds to load as discovered by @venuswku . There needs to be way to quickly load multiple rasters onto the map within 5 seconds or less ideally. `leafmap` and `geemap` have ways of quickly loading rasters from a STAC catalogue that should be investigated.

- [ ] investigate `leafmap` and `geemap` ways of quickly loading imagery on the map
- [ ] design or use a pre-existing widget to load rasters onto the map for a time series.
- I believe leafmap already has functions to load timeseries rasters on the map that should be investigated
- [ ]  Find a way to load rasters faster

Some finding from research (thanks to @venuswku)
- Removing multiple tif layers takes less time than loading tifs. One case took 0.0017 seconds to remove the 4 images
-  an XML file is created for each tif file that was loaded onto the map. 
- Takes roughly 0.2 seconds less time to load the tif files again when the xml files were already created

**Comment by dbuscombe-usgs** [comment]
It seems plausible that if we can simultaneously download imagery and generate XML files, that should speed up rendering of the image on the map?

**Comment by 2320sharon** [comment]
> It seems plausible that if we can simultaneously download imagery and generate XML files, that should speed up rendering of the image on the map?

Sounds like you're suggesting a workflow similar to this.
1. Downloading imagery starts
2. One set of tifs finishes downloading
3.  Those tif are turned into the merge multispectral tif
4. That merged multispectral is loaded onto the map while the rest of the downloads finish

Does this sound like your idea? 

We can provide the user the option to turn off loading of the rasters on the map as they download to prevent the possibility of crashing leafmap too. Of course, all this hinges on the capability of leafmap to be updated asynchronous by multiple threads which I don't even know if its possible.

**Comment by dbuscombe-usgs** [comment]
Yes, that is the idea

I'm not sure how the xml file is being generated by leafmap, but perhaps 
a) we dont need to use leafmap for this, i.e. we can have code run in the background that creates an xml file as soon as a merge multispectral tif is made
b) if concurrency can't be reliably achieved using leafmap, we could always use a OS subprocess?

**Comment by 2320sharon** [comment]
After experimentation with loading rasters on the map and loading jpgs on the map, we've determined the fastest way to load multiple images on the map is to convert the `.tiff` files to `.jpg`. This approach is the one currently implemented.
